dataset: "Herbikher" # change this

path:
  corpus_path: "../yiddish-tts/Herbikher" # change this
  lexicon_path: "lexicon/herbikher-lexicon.txt" # change this
  raw_path: "../yiddish-tts/Herbikher" # change this
  preprocessed_path: "./preprocessed_data/Herbikher" # change this

preprocessing:
  val_size: 512
  text:
    text_cleaners: ["yiddish_cleaners"] # change this add method to text/cleaners.py
    language: "yi" # change this
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
  energy:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
